language: node_js
sudo: false
node_js:
  - 6
  - 8
  - 10
notifications:
  email:
    on_success: change
    on_failure: always
script:
  - npm run lint
  - npm test
after_script:
  - npm install coveralls
  - 'npm run coverage | coveralls'
